"""
This type stub file was generated by pyright.
"""

import pathlib
from client.args import Args

class PsyncClient:
    args: list[str]
    env: dict[str, str]
    path: pathlib.Path
    def __init__(self, args: list[str], env: dict[str, str], path: pathlib.Path) -> None:
        ...
    
    async def run(self): # -> None:
        ...
    


def rsync(args: Args): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
