"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from enum import Enum

class Mode(Enum):
    Host = ...
    Client = ...


class ReqKind(Enum):
    Open = ...
    Kill = ...


class RespKind(Enum):
    Log = ...
    Error = ...
    Exit = ...
    Okay = ...


@dataclass
class OpenReq:
    path: Path
    args: list[str]
    env: Mapping[str, str]
    kind: ReqKind = ...


@dataclass
class KillReq:
    kind: ReqKind = ...


@dataclass
class LogResp:
    msg: str
    kind: RespKind = ...


@dataclass
class ExitResp:
    exit_code: str
    kind: RespKind = ...


@dataclass
class ErrorResp:
    msg: str
    kind: RespKind = ...


@dataclass
class OkayResp:
    kind: RespKind = ...


Req = OpenReq | KillReq
Resp = LogResp | ExitResp | ErrorResp | OkayResp
def serialize(msg: Req | Resp) -> str:
    ...

path_expr = ...
env_expr = ...
args_expr = ...
parse_env_expr = ...
def deserialize_env(input: str) -> dict[str, str]:
    ...

def deserialize(msg: str) -> Req | Resp:
    ...

